# NumPy

In [2]:
import numpy as np


#### Creating a two dimentional array


arr = np.array([[1,2],[2,4],[2,3]])


In [46]:
print(arr.shape)

(3, 2)


In [8]:
y = arr + 3.2

In [9]:
print(y)

[[4.2 5.2]
 [5.2 7.2]
 [5.2 6.2]]


#### Difference between Formatted and unformatted

In [28]:

allones = np.ones((3,2), dtype='i4')

###No format
allones2 = np.ones((3,2))

In [29]:
print(allones)

###Original one without formatting
print(allones2)

[[1 1]
 [1 1]
 [1 1]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Multiplication by dot

In [31]:

mult = np.dot(arr, allones.reshape((2,3)))


In [32]:
print(mult)

[[3 3 3]
 [6 6 6]
 [5 5 5]]


#### Array slicing

In [40]:

first_row = mult[0]
print('Resultant first row:' ,first_row)

Resultant first row: [3 3 3]


#### To get sum of all sliced

In [44]:
sum = np.sum(first_row)

In [45]:
print(sum)

9


# All Done!

#### Tiling is used to repeat arrays. For instance,

In [51]:
    totile = np.array([1,2])
    print(totile)
    tiled = np.tile(totile,4)

[1 2]


In [52]:
print(tiled)

[1 2 1 2 1 2 1 2]
