# NumPy

In [2]:
import numpy as np

In [6]:
##Creating a two dimentional array
arr = np.array([[1,2],[2,4],[2,3]])


In [7]:
print(arr.shape)

(3, 2)


In [8]:
y = arr + 3.2

In [9]:
print(y)

[[4.2 5.2]
 [5.2 7.2]
 [5.2 6.2]]


In [28]:
###Formatted with type i4
allones = np.ones((3,2), dtype='i4')

###No format
allones2 = np.ones((3,2))

In [29]:
print(allones)

###Original one without formatting
print(allones2)

[[1 1]
 [1 1]
 [1 1]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
###Multiplication by dot
mult = np.dot(arr, allones.reshape((2,3)))


In [32]:
print(mult)

[[3 3 3]
 [6 6 6]
 [5 5 5]]


In [40]:
###Array slicing

first_row = mult[0]
print('Resultant first row:' ,first_row)

Resultant first row: [3 3 3]


In [44]:
###To get sum of all sliced
sum = np.sum(first_row)

In [45]:
print(sum)

9


In [ ]:
# All Done!